spring:
  application:
    name: prices
  datasource:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
